config/routes.rb
Todola::Application.routes.draw do
  devise_for :users

  namespace :api do
    resources :tokens, only: [:create, :destroy]
    
    resources :tasks do
      member do
        put :complete, :uncomplete
      end
    end
  end

  resources :tasks do
    member do
      post :toggle_complete
    end
  end

  root to: 'pages#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  PRIORITIES = {
    1 => :high,
    2 => :medium,
    3 => :low
  }

  attr_accessible :name, :priority, :due_date, :due_date_fmt

  belongs_to :user

  validates :name, :state, presence: true
  validates :name, length: { maximum: 255 }
  validates :priority, inclusion: { in: PRIORITIES.keys }, allow_nil: true

  state_machine :state, initial: :pending  do
    state :pending
    state :completed

    event :complete do
      transition pending: :completed
    end

    event :uncomplete do
      transition completed: :pending
    end
  end

  def as_json(options = {})
    super(options.merge(
      only: [:id, :name, :due_date, :priority, :created_at]
    ))
  end

  def errors_a
    errors.map {|k, v| [k, v] }
  end

  def toggle_complete!
    completed? ? uncomplete! : complete!
  end

  def priority_sym
    PRIORITIES[priority]
  end

  def due_date_fmt=(value)
    self.due_date = Date.strptime(value, '%m/%d/%Y') + 1.minute rescue nil
  end

  def due_date_fmt
    due_date.strftime('%m/%d/%Y') if due_date
  end

  def self.search(attribute, direction)
    attribute ||= 'id'
    direction ||= 'DESC'

    order("#{attribute} #{direction} NULLS LAST")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
    :rememberable, :trackable, :validatable, :token_authenticatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :tasks, dependent: :destroy
  
  before_save :ensure_authentication_token
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  # TODO: add not found exception handler
  rescue_from Exception, with: :error_render_method

  skip_before_filter :verify_authenticity_token
  respond_to :json

  protected

  def ok_response(response = {})
    response[:status] = 'OK'
    render status: 200, json: response
  end

  def error_response(error_code, response = {})
    response[:status] = error_code
    render status: 401, json: response
  end

  def authenticate_user!
    if params[:auth_token].blank? || !User.exists?(authentication_token: params[:auth_token])
      error_response("UNAUTHORIZED")
    end
  end

  def error_render_method(exception)
    Rails.logger.error(exception.backtrace.join("\n"))
    error_response('INTERNAL_ERROR')
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < Api::BaseController
  before_filter :authenticate_user!
  before_filter :find_task, only: [:show, :destroy, :update, :complete, :uncomplete]

  def show
    ok_response(task: @task)
  end

  def create
    @task = current_user.tasks.create(task_params)

    if @task.persisted?
      ok_response(task: @task)
    else
      error_response('INVALID', errors: @task.errors_a )
    end
  end

  def index
    @tasks = current_user.tasks.search(params[:sort_by], params[:direction])
    ok_response(tasks: @tasks)
  end

  def destroy
    @task.destroy
    ok_response
  end

  def update
    if @task.update_attributes(task_params)
      ok_response(task: @task)
    else
      error_response('INVALID', errors: @task.errors_a)
    end
  end

  def complete
    if @task.complete
      ok_response(task: @task)
    else
      error_response('INVALID_TRANSITION')
    end
  end

  def uncomplete
    if @task.uncomplete
      ok_response(task: @task)
    else
      error_response('INVALID_TRANSITION')
    end
  end

  protected

  def task_params
    params.slice(:name, :priority, :due_date, :due_date_fmt)
  end

  def find_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/controllers/api/tokens_controller.rb
class Api::TokensController < Api::BaseController
  def create
    if params[:email].blank? || params[:password].nil?
      error_response('BLANK')
    else
      if user = User.find_by_email(params[:email].downcase)
        # http://rdoc.info/github/plataformatec/devise/master/Devise/Models/TokenAuthenticatable
        user.ensure_authentication_token!

        if user.valid_password?(params[:password])
          ok_response(:auth_token => user.authentication_token)
        else
          error_response('INCORRECT')
        end
      else
        error_response('INCORRECT')
      end
    end
  end

  def destroy
    if user = User.find_by_authentication_token(params[:id])
      user.reset_authentication_token!
      ok_response(token: params[:id])
    else
      error_response('INVALID')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to tasks_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_tasks, only: [:index, :update]
  before_filter :find_task, only: [:toggle_complete, :destroy, :update, :edit]

  def index
  end

  def create
    @task = current_user.tasks.create(params[:task])
  end

  def destroy
    @task.destroy
  end

  def update
    @task.update_attributes(params[:task])
  end

  def edit
  end

  def toggle_complete
    @task.toggle_complete!
  end

  private

  def find_tasks
    @tasks = current_user.tasks.search(sort_by, direction)
  end

  def find_task
    @task = current_user.tasks.find(params[:id])
  end

  def sort_by
    params[:sort_by] if %w{due_date priority}.include?(params[:sort_by])
  end

  def direction
    params[:direction] if %w{asc desc}.include?(params[:direction])
  end
end

app/helpers/application_form_builder.rb
class ApplicationFormBuilder < ActionView::Helpers::FormBuilder
  def error_messages_on(attribute)
    if object.errors.include?(attribute)
      errors = object.errors[attribute].join("<br/>")
      %{<div class="help-inline">#{errors}</div>}.html_safe
    end
  end

  def control_group(attribute, &block)
    content = @template.capture(&block)
    error_class = object.errors.include?(attribute) && 'error'

    %{<div class="control-group #{error_class}">#{content}</div>}.html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ActionView::Base.default_form_builder = ApplicationFormBuilder
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  TASK_PRIORITY_TO_CLASS = {
    high: :important,
    medium: :warning,
    low: :info
  }

  def tasks_sort_link(attribute)
    title = Task.human_attribute_name(attribute)
    current_attribute = (params[:sort_by] == attribute)
    css_class = "current" if current_attribute
    direction = (current_attribute && params[:direction] == "asc") ? "desc" : "asc"
    arrow = %{<i class="icon-arrow-#{direction == 'asc' ? :up : :down}"></i>} if current_attribute

    link_to "#{title} #{arrow}".html_safe, tasks_path(sort_by: attribute, direction: direction), 
      { remote: true, class: css_class }
  end

  def task_priority_label(task)
    if task.priority
      text = t(task.priority_sym, scope: 'task.priorities')
      label_class = TASK_PRIORITY_TO_CLASS[task.priority_sym]

      %{<span class="label label-#{label_class}">#{text}</span>}.html_safe
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= @title || "Todola"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .container
      - if user_signed_in?
        .navbar.navbar-inverse
          .navbar-inner
            .container-fluid
              %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.brand{ href: root_path } Todola
              .nav-collapse.collapse
                %p.navbar-text.pull-right
                  Logged in as
                  %a.navbar-link{:href => "#"}= current_user.email
                  = link_to 'Logout', destroy_user_session_path, method: :delete

      = yield
    
      %footer
        %p &copy; Mikhail Khomutetckii. Todola App 2013


    = javascript_include_tag "application"

app/views/tasks/_edit.html.haml
.modal.hide.fade.edit-task
  .modal-header
    %h3 Edit Task

  .modal-body
    = form_for @task, remote: true, html: { class: 'form-horizontal' } do |f|
      .control-group
        = f.label :name, 'Task name', class: 'control-label'
        .controls
          = f.text_field :name, placeholder: 'Task name', maxlength: 255

      .control-group
        = f.hidden_field :priority
        = f.label :priority, class: 'control-label'
        .controls
          = render 'priority_select', task: @task

      .control-group
        = f.label :due_date_fmt, 'Due date', class: 'control-label'
        .controls
          = f.text_field :due_date_fmt, placeholder: 'mm/dd/yyyy', class: 'due-date'

  .modal-footer
    %button.btn(data-dismiss="modal" aria-hidden="true") Close
    %button.btn.btn-primary.submit(data-dismiss="modal") Save changes

app/views/tasks/_new.html.haml
= form_for Task.new, remote: true, html: { class: 'new-task form-horizontal' } do |f|
  = f.text_field :name, placeholder: 'Task name', maxlength: 255

  = f.hidden_field :priority
  = render 'priority_select', task: f.object

  = f.text_field :due_date_fmt, placeholder: 'mm/dd/yyyy', class: 'due-date'
  %button.btn(type="submit")
    %i.icon-plus-sign
    Add

app/views/tasks/_priority_select.html.haml
.btn-group.priorities(data-toggle="buttons-radio")
  %button.btn.btn-mini.btn-danger(type="button" data-value="1"){class: task.priority == 1 && 'active'} High
  %button.btn.btn-mini.btn-warning(type="button" data-value="2"){class: task.priority == 2 && 'active'} Medium
  %button.btn.btn-mini.btn-info(type="button" data-value="3"){class: task.priority == 3 && 'active'} Low

app/views/tasks/_task.html.haml
%tr.task{id: dom_id(task), 'data-id' => task.id, class: task.completed? && 'completed'}
  %td
    = form_tag toggle_complete_task_path(task), method: :post, remote: true, class: 'complete-task' do
      = check_box_tag :complete, '1', task.completed?
  %td.name
    = task.name
    - if task.completed?
      %span.label.label-success Completed
  %td.priority= task_priority_label(task)
  %td.due-date
    = task.due_date.to_s(:month_date_year) if task.due_date
  %td.actions
    = link_to edit_task_path(task), remote: true do
      %i.icon-edit
    = link_to task, method: :delete, remote: true, confirm: 'Are you really want to remove?' do
      %i.icon-trash

app/views/tasks/_tasks.html.haml
%table.table.table-striped.tasks-list
  - unless @tasks.empty?
    %thead
      %tr
        %th
        %th
        %th= tasks_sort_link('priority')
        %th= tasks_sort_link('due_date')
        %th
  %tbody
    = render @tasks

app/views/tasks/complete.js.haml
$('##{dom_id(@task)}').replaceWith('#{j render @task}');

app/views/tasks/create.js.haml
- if @task.errors.empty?
  $('.tasks-list').prepend('#{j render @task}');

$('#new_task').trigger('empty')

app/views/tasks/destroy.js.haml
$('##{dom_id(@task)}').hide()

app/views/tasks/edit.js.haml
$('#{j render 'edit'}').modal('show');

$(document).trigger('edit_task.shown');

app/views/tasks/index.html.haml
.tasks
  %h1 My Tasks

  = render 'new'
  = render 'tasks'

app/views/tasks/index.js.haml
$('.tasks-list').replaceWith('#{j render 'tasks'}');

app/views/tasks/toggle_complete.js.haml
$('##{dom_id(@task)}').replaceWith('#{j render @task}');

app/views/tasks/update.js.haml
$('.tasks-list').replaceWith('#{j render 'tasks'}');